disabled_rules: # rule identifiers to exclude from running
  - colon # exaclty one space after the : >>> let abc: Void\n
  - todo # TODO can be written in the code but should be linked to a ticket on JIRA.
  - nesting # func nesting max 1 level
  - empty_parentheses_with_trailing_closure
  - trailing_whitespace
included: # paths to include during linting. `--path` is ignored if present.
  - ChineseWordCard
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - ChineseWordCard/SettingData.swift
  - ChineseWordCard/ChineseWord.swift

file_length:
  - 600 #warning
  - 800 #error

function_body_length:
  - 40 #warning
  - 80 #error

line_length:
  - 300 #warning
  - 350 #error

type_body_length:
  - 400 #warning
  - 500 #error

opt_in_rules:
 # - missing_docs
  - force_unwrapping
  - control_statement
  - private_outlet
  - vertical_whitespace
