disabled_rules: # rule identifiers to exclude from running
  - colon # exaclty one space after the : >>> let abc: Void\n
  - todo # TODO can be written in the code but should be linked to a ticket on JIRA.
  - nesting # func nesting max 1 level
  - trailing_whitespace

included: # paths to include during linting. `--path` is ignored if present.
  - ChineseWordCard

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - ChineseWordCard/SettingData.swift
  - ChineseWordCard/ChineseWord.swift

file_length:
  - 1000 #warning
  - 1500 #error

function_body_length:
  - 200 #warning
  - 400 #error

line_length:
  - 500 #warning
  - 750 #error

type_body_length:
  - 400 #warning
  - 500 #error

opt_in_rules:
  - force_unwrapping
  - control_statement
  - private_outlet
  - vertical_whitespace
